# Generated by Django 4.0.5 on 2022-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
